// <auto-generated />
using System;
using Dashboard.Brokers.Storages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dashboard.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20250904073622_CreateAllTablesInitializeAddTable")]
    partial class CreateAllTablesInitializeAddTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Models.BudgetData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Defense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Education")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Healthcare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Infrastructure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Other")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("BudgetDatas");
                });

            modelBuilder.Entity("Dashboard.Models.CurrencyRateData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EurToUzs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsdToUzs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("CurrencyRateDatas");
                });

            modelBuilder.Entity("Dashboard.Models.DemographyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<double>("RuralPercent")
                        .HasColumnType("float");

                    b.Property<double>("UrbanPercent")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("DemographyDatas");
                });

            modelBuilder.Entity("Dashboard.Models.DemographyGenderData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Female")
                        .HasColumnType("bigint");

                    b.Property<long>("Male")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("DemographyGenderDatas");
                });

            modelBuilder.Entity("Dashboard.Models.GdpData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("GdpDatas");
                });

            modelBuilder.Entity("Dashboard.Models.InflationData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("InflationDatas");
                });

            modelBuilder.Entity("Dashboard.Models.SectorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Agriculture")
                        .HasColumnType("float");

                    b.Property<double>("Industry")
                        .HasColumnType("float");

                    b.Property<double>("Services")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("SectorDatas");
                });

            modelBuilder.Entity("Dashboard.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Dashboard.Models.TradeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Export")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("TradeDatas");
                });

            modelBuilder.Entity("Dashboard.Models.UnemploymentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("UnemploymentDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
